name: Deploy Typrr

on:
  push:
    branches: ["main"]

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-central-1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    # AWS login via OIDC
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::242046727288:role/github-actions-typrr
        aws-region: ${{ env.AWS_REGION }}

    # Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      working-directory: terraform
      run: terraform init

    # Load outputs
    - name: Load Terraform outputs
      working-directory: terraform
      run: |
        echo "ECR_URL=$(terraform output -raw backend_ecr_url)" >> $GITHUB_ENV
        echo "ECS_CLUSTER=$(terraform output -raw ecs_cluster_name)" >> $GITHUB_ENV
        echo "ECS_SERVICE=$(terraform output -raw backend_service_name)" >> $GITHUB_ENV
        echo "S3_BUCKET=$(terraform output -raw frontend_bucket_name)" >> $GITHUB_ENV
        echo "CLOUDFRONT_ID=$(terraform output -raw cloudfront_distribution_id)" >> $GITHUB_ENV

    # Login to ECR
    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2

    # Build backend
    - name: Build backend image
      run: |
        docker build -t typrr-backend ./typrr-backend

    # Tag image
    - name: Tag image
      run: |
        docker tag typrr-backend:latest $ECR_URL:latest

    # Push image
    - name: Push image
      run: |
        docker push $ECR_URL:latest

    # Run database migrations
    - name: Run Prisma migrations
      run: |
        aws ecs run-task \
          --cluster $ECS_CLUSTER \
          --launch-type FARGATE \
          --task-definition $ECS_SERVICE \
          --network-configuration "awsvpcConfiguration={subnets=[subnet-0e7de6c8fc870b9e4,subnet-066ec7f6416aa77cc],securityGroups=[sg-0254308430abf1e2e],assignPublicIp=ENABLED}" \
          --overrides '{
            "containerOverrides": [{
              "name": "backend",
              "command": ["sh","-c","npx prisma migrate deploy"]
            }]
          }'

    # Deploy ECS
    - name: Deploy ECS
      run: |
        aws ecs update-service \
          --cluster $ECS_CLUSTER \
          --service $ECS_SERVICE \
          --force-new-deployment

    # Build frontend
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Install frontend dependencies
      working-directory: typrr-frontend
      run: npm ci

    - name: Build frontend
      working-directory: typrr-frontend
      run: npm run build

    # Upload frontend
    - name: Upload frontend to S3
      run: |
        aws s3 sync typrr-frontend/dist s3://$S3_BUCKET --delete

    # Invalidate CloudFront
    - name: Invalidate CloudFront
      run: |
        aws cloudfront create-invalidation \
          --distribution-id $CLOUDFRONT_ID \
          --paths "/*"